#!/usr/bin/env python3
"""Render the human Spine from registry.json without maintaining a second truth."""

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent
REGISTRY = ROOT / "registry.json"
OUTPUT = ROOT / "SPINE.md"


def cell(value):
    if isinstance(value, list):
        value = ", ".join(str(item) for item in value)
    return str(value or "").replace("|", "\\|").replace("\n", " ")


def render(spine):
    lines = [
        "<!-- Generated by render_spine.py from registry.json. Do not edit by hand. -->",
        "",
        "# The RAPP Spine — `rapp-spine/1.0`",
        "",
        "> **`registry.json` + `foundation.json` are authoritative.** This file is a",
        "> deterministic human rendering of `registry.json`; `python3 render_spine.py --check`",
        "> fails if it drifts.",
        "",
        spine["doctrine"],
        "",
        "## How to crawl",
        "",
        "- **AI:** fetch `registry.json`, match the concrete situation against `router`, then follow the selected registry entry.",
        "- **Human/script:** run `python3 crawl.py \"<situation>\"`.",
        "- **Integrity:** run `python3 verify_spine.py --local`.",
        "",
        "## Router — situation → protocol",
        "",
        "| Situation | Use | Why |",
        "|---|---|---|",
    ]
    for route in spine["router"]:
        lines.append(
            f"| {cell(route['situation'])} | {cell(route['use'])} | {cell(route['why'])} |"
        )

    lines.extend(
        [
            "",
            "## Column — " + " · ".join(spine["layers_order"]),
            "",
        ]
    )
    for layer in spine["layers"]:
        lines.extend(
            [
                f"### {layer['layer']}",
                "",
                layer["summary"],
                "",
                f"**Protocols:** {cell(layer['protocols'])}",
                "",
            ]
        )

    lines.extend(
        [
            "## Registry — every vertebra",
            "",
            "| Spec | Repository | Layer | Purpose / when to use | Entry point |",
            "|---|---|---|---|---|",
        ]
    )
    for entry in spine["registry"]:
        purpose = entry.get("when_to_use") or entry.get("role") or entry.get("purpose")
        lines.append(
            f"| `{cell(entry['spec_id'])}` | {cell(entry['repo'])} | {cell(entry['layer'])} | "
            f"{cell(purpose)} | {cell(entry.get('entry_point'))} |"
        )

    lines.extend(["", "## Collisions and gaps", ""])
    for collision in spine["collisions_and_gaps"]:
        lines.append(f"- {collision}")

    lines.extend(
        [
            "",
            f"*Generated from `registry.json` ({spine.get('generated', 'unknown')}).*",
            "",
        ]
    )
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    with REGISTRY.open(encoding="utf-8") as handle:
        rendered = render(json.load(handle))

    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != rendered:
            raise SystemExit("SPINE.md is stale; run python3 render_spine.py")
        return

    OUTPUT.write_text(rendered, encoding="utf-8")


if __name__ == "__main__":
    main()
